version: "3"
services:
  server:
    image: node:alpine
    working_dir: "/server"
    volumes:
      - ./server:/server
    command: ["npm", "run", "watch-server"]
    ports:
      - "5000:5000"
  front:
    image: node:alpine
    working_dir: "/front"
    volumes:
      - ./front:/front
    command: ["npm", "run", "start"]
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    working_dir: "/etc/nginx"
    volumes:
      - ./nginx:/etc/nginx
    command: ["service", "nginx", "start"]
    ports:
      - "80:80"
    links:
      - server
      - front
